development:
  adapter: postgresql
  database: torako_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: torako_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: torako_production
  pool: 5
  timeout: 500